from . import patient
from . import doctor
from . import appointment
from . import room
from . import treatment
from . import res_groups
from . import res_users
from . import producttemplate
from . import product
from . import mrp_boom_line
from . import account_move
from . import account_move_line
from . import sale_order_line
from . import product_template